### ISSUE TITLE
Exception has occurred: KeyError 'security'

### ISSUE THREAD

**Issue by zhanglongqi** [python-sdbus/python-sdbus-networkmanager#46]
I tried `list-connections-async.py` and `list-connections.py`. both of them have the same issue.

![image](https://user-images.githubusercontent.com/956693/215438509-9413490d-c07e-436a-9497-09a2f6868e05.png)

**Comment by igo95862** [comment]
Hello,

I can replicate this when trying to parse a Wifi Access Point parameters. Apparently it has a deprecated key `security`. My setting generation algorithm simply removes any setting that has a `deprecated` in its description. I will have to modify that.

**Comment by igo95862** [comment]
Should be fixed with 457949f745db8a45f81ac9e9970e45905c416bdc
