### ISSUE TITLE
class defination with parameters

### ISSUE THREAD

**Issue by zhanglongqi** [python-sdbus/python-sdbus-networkmanager#47]
How the `interface_name` works in the class definition? Could you share a link to the doc for this kind of syntax?
 
```python
class NetworkManagerInterface(
        DbusInterfaceCommon,
        interface_name='org.freedesktop.NetworkManager'):
```

**Comment by igo95862** [comment]
Hello,

It is not a syntax. It is a simple string with some limitation imposed by D-Bus specification: https://dbus.freedesktop.org/doc/dbus-specification.html#message-protocol-names-interface

It should be unique between different vendors so by convention a reverse order DNS name is used.

**Comment by zhanglongqi** [comment]
I do not know how the python syntax works. so the `interface_name` is a static member that belongs to the `NetworkManagerInterface`? what is the difference between this and the parameters in `def __init__()`?

**Comment by igo95862** [comment]
`interface_name` is just a class keyword parameter. For `DbusInterfaceCommon` this means it will mark all declared D-Bus elements as belonging to this particular interface name.

See metaclasses PEP to lean more: https://peps.python.org/pep-3115/#specification

> what is the difference between this and the parameters in `def __init__()`?

Init will initialize a particular object. Class parameter affect the class definition and all objects initialized from this class.
