### ISSUE TITLE
add python-sdbus-modemmanager

### ISSUE THREAD

**Issue by zhanglongqi** [python-sdbus/python-sdbus-networkmanager#48]
I just drafted [python-sdbus-modemmanager](https://github.com/zhanglongqi/python-sdbus-modemmanager), maybe you can add this to  https://github.com/python-sdbus

**Comment by igo95862** [comment]
Hello @zhanglongqi 

I added your binds to the python-sdbus README page under community interfaces: https://github.com/python-sdbus/python-sdbus#community-interfaces
