### ISSUE TITLE
Apply updated settings

### ISSUE THREAD

**Issue by Benik3** [python-sdbus/python-sdbus-networkmanager#52]
Hello again.

I successfully made a program to change IP address on interface (static and DHCP) using the example.
The settings is updated, I can see it in NetworkManager GUI, but it's not applied.

I tried to go through the manual but didn't find any option to apply or reconnect the interface so the new setting is immediately used.
Is there any way to achieve it?

Thank you

**Comment by igo95862** [comment]
Hello.

I believe the proper way to do it is to replace the `ActiveConnection` object.

First find the path of the `ActiveConnection` of a particular `Connection`.  You can use [`active_connection`](https://python-sdbus-networkmanager.readthedocs.io/en/latest/device_interfaces.html#sdbus_async.networkmanager.NetworkManagerDeviceInterfaceAsync.active_connection) property of the connection object.

Then you can deactivate that connection using [`deactivate_connection`](https://python-sdbus-networkmanager.readthedocs.io/en/latest/other_interfaces.html#sdbus_async.networkmanager.NetworkManagerInterfaceAsync.deactivate_connection) method of main NetworkManager object. 

After that you can create a new active connection using [`activate_connection`](https://python-sdbus-networkmanager.readthedocs.io/en/latest/other_interfaces.html#sdbus_async.networkmanager.NetworkManagerInterfaceAsync.activate_connection) method of main NetworkManager object. Use the D-Bus path of the connection object and `/` for two other arguments.

**Comment by igo95862** [comment]
I have this script to change an exit point for a wireguard vpn:

```python
nm = NetworkManager()

mullvad_dev = NetworkDeviceWireGuard(nm.get_device_by_ip_iface('mlvd-vpn'))

mullvad_dev_active_connection = mullvad_dev.active_connection
mullvad_active_connection = ActiveConnection(
    mullvad_dev.active_connection,
)


mullvad_connection_path = mullvad_active_connection.connection
mullvad_connection = NetworkConnectionSettings(
    mullvad_connection_path,
)

mullvad_profile = mullvad_connection.get_profile()

mullvad_profile.wireguard.peers = [
    WireguardPeers(
        public_key=public_key,
        endpoint=ipv4_addr,
        allowed_ips=[
            '::/0',
            '0.0.0.0/0',
        ]
    )
]

mullvad_connection.update_profile(mullvad_profile)

nm.deactivate_connection(mullvad_dev_active_connection)
nm.activate_connection(mullvad_connection_path, "/", "/")
```

**Comment by Benik3** [comment]
Thanks, I will try it :)

**Comment by igo95862** [comment]
> Only negative of this solution is hardcoded Device Wired.

You can probably use [connection UUIDs](https://python-sdbus-networkmanager.readthedocs.io/en/latest/other_interfaces.html#sdbus_async.networkmanager.NetworkManagerSettingsInterfaceAsync.get_connection_by_uuid) to have a persistent handle on the particular connection object.

**Comment by igo95862** [comment]
Generally the interface classes should not be used directly because they always require a service and object path. The service path is always know and object path might be known for some objects.

The reason why they are split in the documentation is because I could not make the autodoc from sphinx to document the D-Bus methods that are inherited.

**Comment by Benik3** [comment]
Ah, OK. Yes, with NetworkManagerSettings I was able to get it to work.
But hen I realized, that it returns connection_path, but the hard coded problem was "device_path" :D
Maybe do it in reverse way: get all active connections using D-Bus NetworkManager properties ActiveConnections and find the right connection using iface/uuid/whatever will be presented in the object

**Comment by igo95862** [comment]
You can get the active connection from the connection object using `active_connection` property. This will eliminate the device object entirely.

**Comment by Benik3** [comment]
I don't see active_connection property elsewhere then on device.
Anyway I missed that I can use DeviceGeneric which also solves the problem :)

**Comment by igo95862** [comment]
I was wrong. There is no property that point from a connection to active connection.
