### ISSUE TITLE
Enable/disable wireless interface

### ISSUE THREAD

**Issue by thesems** [python-sdbus/python-sdbus-networkmanager#53]
I'm trying to enable the wireless device/interface via this library. However, I believe it is not implemented.

File: networkmanager/interfaces_other.py
```
@dbus_property_async('b')
    def wireless_enabled(self) -> bool:
        """Whether wireless enabled or not"""
        raise NotImplementedError
```

This suggests its read-only. There is also a method NetworkManager.enable() but it is not capable of turning on the wireless interface.
It would appear that a @dbus_method_async is necessary.

Any plans to implement it or is it enabled in some other way?

Best regards.

**Comment by igo95862** [comment]
Disregard the part about adding setter.

Just call `set_async` with `True` or `False` and await on result. The presence of setter is not checked for a remote objects.

**Comment by thesems** [comment]
Thank you, you are right.
