### ISSUE TITLE
ipv4.dchp-timeout string

### ISSUE THREAD

**Issue by proximous** [python-sdbus/python-sdbus-networkmanager#54]
This is really a feature request.

ipv4.dchp-timeout can take a string of "default" or "infinity" instead of an int. Is it possible to support that also?

**Comment by igo95862** [comment]
Hello @proximous ,

Looking at the documentation the `dchp-timeout` only accepts int32:

https://networkmanager.dev/docs/api/latest/settings-ipv4.html

I looked at the NetworkManager source code. It looks like `"infinity"` value is actually G_MAXINT32 which is 2147483647. Maybe -1 also works as infinity.

https://github.com/NetworkManager/NetworkManager/blob/35eb9c30aa7e51737f8038388c8a52682625f108/src/core/dhcp/nm-dhcp-client.h#L14

Default is most likely used when a value of 0 is passed.

**Comment by proximous** [comment]
Ok. Maybe this is a feature of nmcli, since the following definitely works:

`nmcli c m 'Wired connection 1' ipv4.dhcp-timeout default`

and 

`nmcli c m 'Wired connection 1' ipv4.dhcp-timeout infinity`

But you are correct, I can just use 0 for default and 2147483647 for infinity, so it would be nice to be convenient like nmcli but it's not a critical need.

**Comment by proximous** [comment]
Ok. Thanks for taking the time to look at it.
