### ISSUE TITLE
VPN connection

### ISSUE THREAD

**Issue by andrey-pr** [python-sdbus/python-sdbus-networkmanager#57]
Hello. Could you please show me example how to estabilish VPN connection with python-sdbus-networkmanager? Thank you

**Comment by igo95862** [comment]
Hello.

First of all what kind of VPN?

**Comment by andrey-pr** [comment]
OpenVPN (with my own server)

**Comment by igo95862** [comment]
First of all you will need the plugin for NetworkManager: https://github.com/NetworkManager/NetworkManager-openvpn

**Comment by andrey-pr** [comment]
I have it. I can connect from GUI or CLI, but I need example of doing it from python code

**Comment by igo95862** [comment]
Actually not entirely sure. The upstream documentation does not have details on VPN connections.

Maybe dumping the D-Bus traffic that the CLI does will reveal the exact messages it uses to setup the connection. 

See `busctl monitor`: https://www.freedesktop.org/software/systemd/man/busctl.html#monitor%20SERVICE

(don't forget to replace any secrets in the dump)

**Comment by igo95862** [comment]
I managed to capture the message. I will try to create a new example with the OpenVPN.

**Comment by andrey-pr** [comment]
Created PR. Pls check & merge
