### ISSUE TITLE
Version inconsistency problem having to do with DeviceCapabilitiesFlags/DeviceCapabilities

### ISSUE THREAD

**Issue by marcsmerlin** [python-sdbus/python-sdbus-networkmanager#62]
I just wanted to bring a what I think is a small version inconsistency problem to your attention. I installed the module using:

pip install --only-binary ':all:' sdbus-networkmanager

as suggested. When trying to run examples/block/device-state,py, reference to DeviceCapabilitiesFlags is unresolved. This is corrected by changing it to DeviceCapabilities which apparently existed in a previous version.

**Comment by igo95862** [comment]
Hello @marcsmerlin 

The version uploaded to PyPI is the 2.0.0

So the examples must be used from the 2.0.0 version: https://github.com/python-sdbus/python-sdbus-networkmanager/tree/2.0.0/examples

Right now the 3.0.0 is under development. The examples for version 3.0.0 are not going to work on 2.0.0

**Comment by marcsmerlin** [comment]
It works just fine. Thanks!

**Comment by igo95862** [comment]
Great!
