### ISSUE TITLE
NmAgentManagerNoSecretsError: No agents were available for this request.

### ISSUE THREAD

**Issue by zcattacz** [python-sdbus/python-sdbus-networkmanager#66]
Most of my wifi connections make `get_profile()` failed with `NmAgentManagerNoSecretsError: No agents were available for this request.` Even though without wifi passwords, everything else of the profile should have been retrievable. 
(`get_settings()` returns correctly (w/o any password key) though the dict values are in tuples.)

```
In [170]: fconns[0].get_profile()
---------------------------------------------------------------------------
NmAgentManagerNoSecretsError              Traceback (most recent call last)
Cell In [170], line 1
----> 1 fconns[0].get_profile()

File ~/pystack3/lib/python3.11/site-packages/sdbus_block/networkmanager/interfaces_other.py:623, in NetworkManagerSettingsConnectionInterface.get_profile(self, fetch_secrets)                                                                                                
    620     secrets_name = next(secrets_name_generator)
    621     while True:
    622         secret_profile = ConnectionProfile.from_dbus(
--> 623             self.get_secrets(secrets_name))
    625         secrets_name = secrets_name_generator.send(secret_profile)
    626 except StopIteration:

File /usr/lib/python3/dist-packages/sdbus/dbus_proxy_sync_method.py:86, in DbusMethodSyncBinded.__call__(self, *args, **kwargs)
     80 else:
     81     rebuilt_args = self.dbus_method._rebuild_args(
     82         self.dbus_method.original_method,
     83         *args,
     84         **kwargs)
---> 86 return self._call_dbus_sync(*rebuilt_args)

File /usr/lib/python3/dist-packages/sdbus/dbus_proxy_sync_method.py:70, in DbusMethodSyncBinded._call_dbus_sync(self, *args)
     66 if args:
     67     new_call_message.append_data(
     68         self.dbus_method.input_signature, *args)
---> 70 reply_message = self.interface._dbus.attached_bus.call(
     71     new_call_message)
     72 return reply_message.get_contents()

NmAgentManagerNoSecretsError: No agents were available for this request.

```

**Comment by igo95862** [comment]
Hello @zcattacz 

Have you tried using the `fetch_secrets=False` argument? It will disable fetching the secret values.

**Comment by zcattacz** [comment]
Thank you, that works. I didn't check the API doc, only the quickstart. Maybe replacing the `No agents were available for this request.` with `try fetch_secrets=False` will be more user friendly :-)

**Comment by igo95862** [comment]
> Maybe replacing the `No agents were available for this request.` with `try fetch_secrets=False` will be more user friendly

The `No agents were available for this request` is exactly what NetworkManager returns as an error message.

Maybe `fetch_secrets` should have 3 values of `no`, `auto` and `force` there auto would consider the `NmAgentManagerNoSecretsError` error as there simply are no secrets.
